name: Terraform Apply

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs: 
    terraform:
        name: Deploy Terraform (Apply)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set Up Terraform Credentials
              run: echo 'credentials "app.terraform.io" { token = "${{ secrets.TFE_TOKEN }}" }' > ~/.terraformrc

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: latest

            - name: Terraform Init
              run: terraform init
            
            - name: Terraform Validate
              run: terraform validate
            
            - name: Terraform Plan
              run: terraform plan 

            - name: Terraform Apply
              run: terraform apply -auto-approve 
