name: Terraform Plan

on:
  pull_request:
    paths:
      - "*.tf"

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: Plan Terraform on PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Terraform Credentials
        run: echo 'credentials "app.terraform.io" { token = "${{ secrets.TFE_TOKEN }}" }' > ~/.terraformrc

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init

      - name: Debug Variables
        run: |
          echo "PORT is ${{ secrets.TF_VAR_PORT }}"
          echo "APP_ENV is ${{ secrets.TF_VAR_APP_ENV }}"
          echo "DATABASE_URL is ${{ secrets.TF_VAR_DATABASE_URL }}"
          echo "GITHUB_REF_NAME is ${{ secrets.TF_VAR_GITHUB_REF_NAME }}"
          # Do not echo jwt_secret or any sensitive values

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
        env:
          TF_VAR_port: ${{ secrets.TF_VAR_PORT }}
          TF_VAR_app_env: ${{ secrets.TF_VAR_APP_ENV }}
          TF_VAR_database_url: ${{ secrets.TF_VAR_DATABASE_URL }}
          TF_VAR_github_ref_name: ${{ secrets.TF_VAR_GITHUB_REF_NAME }}
          TF_VAR_jwt_secret: ${{ secrets.TF_VAR_JWT_SECRET }}
